package SmallBoard::Model::Board;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'SmallBoard::Schema',
    
    connect_info => {
        dsn => 'dbi:SQLite:smallboard.db',
        user => '',
        password => '',
    }
);

=head1 NAME

SmallBoard::Model::Board - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<SmallBoard>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<SmallBoard::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.29

=head1 AUTHOR

Devin Austin

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
