abstract: ~
distribution_type: module
generated_by: Module::Install version 0.640
license: unknown
name: Typeface
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst: 5.7006
  Catalyst::Action::RenderView: 0
  Catalyst::Controller::FormBuilder: 0
  Catalyst::Plugin::Authentication: 0
  Catalyst::Plugin::Authentication::Credential::Password: 0
  Catalyst::Plugin::Authentication::Store::DBIC: 0
  Catalyst::Plugin::Cache: 0
  Catalyst::Plugin::Cache::Store::FastMmap: 0
  Catalyst::Plugin::Captcha: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::PageCache: 0
  Catalyst::Plugin::Server: 0
  Catalyst::Plugin::Server::XMLRPC: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::FastMmap: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Plugin::Textile: 0
  Config::Any::YAML: 0
  DateTime: 0
  DateTime::Format::MySQL: 0
  DateTime::Format::Pg: 0
  HTML::CalendarMonthSimple: 0
  JSON::Syck: 0
  SCGI: 0
  SQL::Translator: 0
  Switch: 0
  XML::Feed: 0
  YAML: 0
version: 0.71
